"""G3-F-D claim-safe narration, subtitle, overlay, and presentation sources."""

from __future__ import annotations

import re
from typing import Any

from .common import DELIVERY_ROOT, ROOT, read_json, write_json, write_text


NARRATION = DELIVERY_ROOT / "narration_source.json"
SUBTITLES = DELIVERY_ROOT / "subtitle_source.json"
PRESENTATION = DELIVERY_ROOT / "presentation_flow.json"


def _narration(
    sequence: int, role: str, text: str, truth: list[str], *, claims: list[str] | None = None,
    metrics: list[str] | None = None, figures: list[str] | None = None,
    innovations: list[str] | None = None, mandatory: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "narration_id": f"NARR-{sequence:02d}", "scene_id": f"SCENE-{sequence:02d}",
        "semantic_role": role, "text_or_localization_source": text,
        "text_id": f"NARR_TEXT_{sequence:02d}", "claim_refs": claims or [], "metric_refs": metrics or [],
        "figure_refs": figures or [], "innovation_refs": innovations or [], "truth_identity": truth,
        "duration_budget": "PENDING_UA_F_001", "mandatory_phrase": mandatory or [],
        "forbidden_phrase": ["SOTA", "state-of-the-art", "industry first", "fully autonomous", "all code was generated by AI", "real NPU improvement"],
        "language_status": "CANONICAL_SEMANTIC_SOURCE_PENDING_UA_F_002",
        "review_status": "CLAIM_VALIDATED_PENDING_UA_F_006",
    }


def _narrations() -> list[dict[str, Any]]:
    return [
        _narration(1, "problem", "Collective communication tuning must choose a schedule, explain the decision, and preserve the evidence boundary of every result.", ["RECONSTRUCTED_FROM_FROZEN_EVIDENCE"], innovations=["INNOV-01"]),
        _narration(2, "architecture", "The system separates CPU_SIM host execution, deterministic simulation, Agent-assisted decisions, and Direct compile/link-only readiness so that no layer borrows a stronger validation identity; real device execution is not included.", ["CPU_EXECUTED", "SIMULATED_ONLY", "DIRECT_COMPILE_LINK_ONLY", "REAL_DEVICE_NOT_EXECUTED"], claims=["C-ABI-001", "C-DIRECT-001"], figures=["FIG-01"], innovations=["INNOV-05"], mandatory=["compile/link-only", "real device not executed"]),
        _narration(3, "mechanism", "A static choice is insufficient across topology and message-scale changes, so the frozen Schedule IR and analytical selector compare explicit schedule candidates under deterministic gates.", ["SIMULATED_ONLY", "DETERMINISTIC_EVALUATION"], figures=["FIG-02"], innovations=["INNOV-02"]),
        _narration(4, "quantitative_evidence", "In the frozen simulated benchmark, the selected schedules achieved 18 wins, 0 ties, and 0 losses. The weighted simulated improvement is 45.59283008 percent raw and 45.59 percent for display; it is not a real Ascend/NPU measurement.", ["SIMULATED_ONLY"], claims=["C-PERF-001", "C-PERF-002"], metrics=["g3b2.performance.weighted_geomean_improvement_percent", "g3b2.outcomes.wins", "g3b2.outcomes.ties", "g3b2.outcomes.losses"], figures=["FIG-03", "FIG-04"], innovations=["INNOV-02"], mandatory=["frozen simulated benchmark", "not a real Ascend/NPU measurement"]),
        _narration(5, "agent_provenance", "This offline replay shows an Agent-generated proposal, deterministic evaluation, reflection and replanning records, and the final decision. It is replayed from a frozen trace, not presented as original historical autonomous execution, and human governance remains disclosed.", ["AGENT_GENERATED", "DETERMINISTIC_EVALUATION", "HUMAN_INTERVENTION", "OFFLINE_REPLAY", "REPLAYED_FROM_FROZEN_TRACE"], figures=["FIG-08"], innovations=["INNOV-01"], mandatory=["offline replay", "not original historical execution", "human governance"]),
        _narration(6, "scale_boundary", "The 1024-rank result is a logical model-scale simulation. It is not a measured 1024-card cluster result.", ["SIMULATED_ONLY"], claims=["C-SCALE-001"], figures=["FIG-05"], mandatory=["logical model-scale", "not a measured 1024-card cluster"]),
        _narration(7, "feature_boundary", "Lossless sparse reconstruction, CRC integrity, and bounded retry are host validated. Sparse wire-byte savings are modeled accounting, while backpressure remains simulated; none of these is NIC or real HCCL hardware validation.", ["LOSSLESS_SPARSE_HOST_EXECUTED", "HOST_INTEGRITY_VALIDATED", "HOST_RETRY_VALIDATED", "SIMULATED_BACKPRESSURE", "REAL_DEVICE_NOT_EXECUTED"], claims=["C-SPARSE-001", "C-CRC-001", "C-RETRY-001", "C-BP-001"], figures=["FIG-06", "FIG-07"], innovations=["INNOV-03", "INNOV-04"], mandatory=["host validated", "modeled accounting", "backpressure remains simulated"]),
        _narration(8, "direct_boundary", "The default-off Direct production source contains 17 official ACL/HCCL call expressions and has compile/link-only readiness evidence. No ACL/HCCL runtime, communicator, collective, or real device was executed.", ["DIRECT_COMPILE_LINK_ONLY", "DIRECT_READINESS_ONLY", "REAL_DEVICE_NOT_EXECUTED"], claims=["C-DIRECT-001", "C-DIRECT-002"], figures=["FIG-10"], innovations=["INNOV-05"], mandatory=["compile/link-only", "no ACL/HCCL runtime", "real device was not executed"]),
        _narration(9, "live_demo", "The live command builds and runs the project-owned CPU_SIM plugin on the host, then replays the Agent trace and verifies registered figures offline. This demonstrates host reproducibility without an API key or NPU and does not rerun the frozen performance benchmark.", ["LIVE_DEMO_CPU_SIM", "DEMO_REPLAY", "REAL_DEVICE_NOT_EXECUTED"], claims=["C-ABI-001"], innovations=["INNOV-05"], mandatory=["CPU_SIM", "host", "without an API key or NPU"]),
        _narration(10, "limitations", "Real-device acceptance remains hardware blocked. The delivery does not claim real Ascend performance, runtime HCCL execution, measured NIC traffic, or hardware backpressure.", ["REAL_DEVICE_NOT_EXECUTED"], claims=["C-DIRECT-002"], figures=["FIG-12"], mandatory=["real-device acceptance remains hardware blocked"]),
        _narration(11, "competition_value", "The competition value is an evidence-governed workflow that connects schedule optimization, Agent-assisted decisions, host-validated reliability, simulated performance, and offline reproducibility while keeping every limitation visible.", ["RECONSTRUCTED_FROM_FROZEN_EVIDENCE", "REAL_DEVICE_NOT_EXECUTED"], figures=["FIG-13"], innovations=["INNOV-01", "INNOV-02", "INNOV-03", "INNOV-04", "INNOV-05"]),
    ]


def _overlays() -> list[dict[str, Any]]:
    return [
        {"badge_id": "SIMULATED_ONLY", "display_text": "SIMULATED ONLY", "required_scenes": ["SCENE-03", "SCENE-04", "SCENE-06"], "claim_boundary": "not real-device performance", "placement": "same frame as the number/figure"},
        {"badge_id": "HOST_VALIDATED", "display_text": "HOST VALIDATED", "required_scenes": ["SCENE-07", "SCENE-09"], "claim_boundary": "host/CPU path only", "placement": "same frame as the result"},
        {"badge_id": "LOGICAL_MODEL_SCALE", "display_text": "LOGICAL MODEL SCALE", "required_scenes": ["SCENE-06"], "claim_boundary": "logical ranks are not physical cards", "placement": "adjacent to rank count"},
        {"badge_id": "DIRECT_COMPILE_LINK_ONLY", "display_text": "DIRECT: COMPILE/LINK ONLY", "required_scenes": ["SCENE-08"], "claim_boundary": "no runtime call execution", "placement": "same frame as Direct flow"},
        {"badge_id": "REAL_DEVICE_NOT_EXECUTED", "display_text": "REAL DEVICE NOT EXECUTED", "required_scenes": ["SCENE-08", "SCENE-09", "SCENE-10", "SCENE-11"], "claim_boundary": "hardware acceptance remains blocked", "placement": "persistent lower-third"},
        {"badge_id": "OFFLINE_REPLAY", "display_text": "OFFLINE REPLAY", "required_scenes": ["SCENE-05"], "claim_boundary": "not original historical execution", "placement": "same frame as replay output"},
    ]


def _flow(profile: str, scene_ids: list[str], narrations: dict[str, dict[str, Any]]) -> dict[str, Any]:
    items = []
    storyboard = {row["scene_id"]: row for row in read_json(DELIVERY_ROOT / "storyboard.json")["scenes"]}
    for index, scene_id in enumerate(scene_ids, 1):
        scene = storyboard[scene_id]
        narration = narrations[scene_id]
        items.append({
            "order": index, "section": scene["section"], "scene": scene_id,
            "figure_or_demo": scene["figure_ref"] or scene["demo_step_ref"],
            "speaker_goal": scene["purpose"], "key_sentence": narration["text_id"],
            "evidence": sorted(set(scene["claim_refs"] + scene["metric_refs"] + scene["trace_refs"] + scene["innovation_refs"])),
            "truth_identity": narration["truth_identity"],
            "expected_audience_takeaway": scene["purpose"],
            "likely_question": "Use the G3-E defense question map for this scene's claim boundary.",
            "fallback": scene["fallback_visual"], "transition": scene["transition"],
        })
    return {"profile": profile, "duration_status": "PRODUCTION_BUDGET_PENDING_UA_F_001", "items": items}


def build_presentation() -> dict[str, Any]:
    narrations = _narrations()
    write_json(NARRATION, {
        "schema_version": "g3-f-narration-source-v1", "status": "PASS",
        "language_status": "USER_ACTION_REQUIRED", "voiceover_created": False,
        "hidden_chain_of_thought_included": False, "segments": narrations,
    })
    subtitles = [{
        "subtitle_id": f"SUB-{index:02d}", "scene_id": f"SCENE-{index:02d}", "narration_id": f"NARR-{index:02d}",
        "text_id": f"NARR_TEXT_{index:02d}", "start_anchor": f"SCENE-{index:02d}:START",
        "end_anchor": f"SCENE-{index:02d}:END", "estimated_duration": "PENDING_UA_F_001",
        "truth_identity": row["truth_identity"], "claim_refs": row["claim_refs"],
        "language_status": "USER_ACTION_REQUIRED",
    } for index, row in enumerate(narrations, 1)]
    write_json(SUBTITLES, {
        "schema_version": "g3-f-subtitle-source-v1", "status": "PASS", "timeline_status": "ANCHORS_ONLY_PENDING_UA_F_001",
        "language_status": "USER_ACTION_REQUIRED", "srt_vtt_created": False, "subtitles": subtitles,
    })
    by_scene = {row["scene_id"]: row for row in narrations}
    flows = [
        _flow("SHORT", ["SCENE-01", "SCENE-02", "SCENE-04", "SCENE-05", "SCENE-09", "SCENE-10", "SCENE-11"], by_scene),
        _flow("STANDARD", [f"SCENE-{index:02d}" for index in range(1, 12)], by_scene),
        _flow("TECHNICAL", [f"SCENE-{index:02d}" for index in range(1, 12)], by_scene),
    ]
    write_json(PRESENTATION, {"schema_version": "g3-f-presentation-flow-v1", "status": "PASS", "flows": flows, "ppt_created": False})
    write_json(DELIVERY_ROOT / "on_screen_truth_badges.json", {
        "schema_version": "g3-f-truth-badges-v1", "status": "PASS", "badges": _overlays(),
        "narration_only_mitigation_allowed": False,
    })
    write_json(DELIVERY_ROOT / "localization_status.json", {
        "schema_version": "g3-f-localization-status-v1", "status": "USER_ACTION_REQUIRED",
        "canonical_semantic_source": "AVAILABLE", "final_language": "UNRESOLVED_UA_F_002",
        "final_timeline": "UNRESOLVED_UA_F_001", "voiceover": "UNRESOLVED_UA_F_003",
        "final_wording": "UNRESOLVED_UA_F_006", "srt_vtt_created": False, "audio_created": False,
    })
    script = ["# G3-F Narration Script", "", "Canonical semantic source; final language, timing, wording, and voice remain USER_ACTION_REQUIRED.", ""]
    for row in narrations:
        script.extend([f"## {row['narration_id']} / {row['scene_id']}", "", row["text_or_localization_source"], "", f"Truth: `{', '.join(row['truth_identity'])}`", ""])
    write_text(DELIVERY_ROOT / "narration_script.md", "\n".join(script))
    flow_md = ["# G3-F Presentation Flow", "", "Durations are production budgets pending UA-F-001; this is not a PPT deck.", ""]
    for flow in flows:
        flow_md.extend([f"## {flow['profile']}", "", " → ".join(row["scene"] for row in flow["items"]), ""])
    write_text(DELIVERY_ROOT / "presentation_flow.md", "\n".join(flow_md))
    write_text(DELIVERY_ROOT / "claim_safe_video_phrasebook.md", """# Claim-Safe Video Phrasebook

## SAFE

- In the frozen simulated benchmark: 18 wins, 0 ties, 0 losses; 45.59% weighted simulated improvement.
- Lossless sparse correctness, CRC/integrity, and bounded retry are host validated.
- Backpressure remains simulated.
- Direct has compile/link-only readiness; real device was not executed.
- The Agent flow is offline replayable, deterministically evaluated, and human governed.

## CONDITIONAL

- “Agent-generated” requires the matching G3-D provenance record.
- “Automatic optimization” must retain Agent-assisted, deterministic-evaluation, and human-governance boundaries.
- “Reference video” must retain `REFERENCE_VIDEO_ONLY` until platform acceptance.

## FORBIDDEN

- Real Ascend performance improved by 45.59%.
- Measured 1024-card cluster.
- Real HCCL validated or runtime collective passed.
- Fully autonomous Agent; all code generated by AI.
- SOTA, state-of-the-art, industry first, or leading without independent authority.
""")
    return validate_presentation()


def _ids(path: Any, collection: str, key: str) -> set[str]:
    return {str(row[key]) for row in read_json(path)[collection]}


def validate_presentation() -> dict[str, Any]:
    errors: list[str] = []
    required = [
        "narration_source.json", "narration_script.md", "subtitle_source.json",
        "presentation_flow.json", "presentation_flow.md", "on_screen_truth_badges.json",
        "claim_safe_video_phrasebook.md", "localization_status.json",
    ]
    for name in required:
        if not (DELIVERY_ROOT / name).is_file():
            errors.append(f"missing artifact: {name}")
    if errors:
        return {"schema_version": "g3-f-presentation-validation-v1", "status": "FAIL", "errors": errors}
    narration = read_json(NARRATION)
    subtitles = read_json(SUBTITLES)
    presentation = read_json(PRESENTATION)
    scenes = _ids(DELIVERY_ROOT / "storyboard.json", "scenes", "scene_id")
    claims = _ids(ROOT / "docs/submission/report_claim_ledger.json", "claims", "claim_id")
    metrics = _ids(ROOT / "docs/submission/report_data_ledger.json", "metrics", "metric_id")
    figures = _ids(ROOT / "docs/submission/visualization/chart_registry.json", "figures", "figure_id")
    innovations = _ids(ROOT / "docs/submission/visualization/innovation_map.json", "innovations", "innovation_id")
    segments = narration.get("segments", [])
    if {row.get("scene_id") for row in segments} != scenes:
        errors.append("narration/scene coverage mismatch")
    forbidden = ["state-of-the-art", "industry first", "fully autonomous", "all code was generated by ai"]
    for row in segments:
        text = row.get("text_or_localization_source", "")
        lower = text.casefold()
        if any(phrase in lower for phrase in forbidden):
            errors.append(f"forbidden narration phrase: {row.get('narration_id')}")
        for name, values, allowed in (
            ("claim", row.get("claim_refs", []), claims), ("metric", row.get("metric_refs", []), metrics),
            ("figure", row.get("figure_refs", []), figures), ("innovation", row.get("innovation_refs", []), innovations),
        ):
            missing = sorted(set(values) - allowed)
            if missing:
                errors.append(f"unresolved {name} refs in {row.get('narration_id')}: {missing}")
        if "45.59" in text and ("simulated" not in lower or "not a real ascend/npu measurement" not in lower):
            errors.append("45.59 narration lost simulation boundary")
        if "1024" in text and ("logical model-scale" not in lower or "not a measured 1024-card" not in lower):
            errors.append("1024 narration lost logical-scale boundary")
        if "direct" in lower and ("compile/link-only" not in lower or ("real device" not in lower and "real-device" not in lower)):
            errors.append("Direct narration lost compile/link/real-device boundary")
    narration_ids = {row["narration_id"] for row in segments}
    text_ids = {row["text_id"] for row in segments}
    subtitle_rows = subtitles.get("subtitles", [])
    if {row.get("narration_id") for row in subtitle_rows} != narration_ids or {row.get("text_id") for row in subtitle_rows} != text_ids:
        errors.append("subtitle/narration mapping mismatch")
    if subtitles.get("timeline_status") != "ANCHORS_ONLY_PENDING_UA_F_001" or subtitles.get("srt_vtt_created") is not False:
        errors.append("subtitle final-timeline boundary violated")
    flows = presentation.get("flows", [])
    if {row.get("profile") for row in flows} != {"SHORT", "STANDARD", "TECHNICAL"}:
        errors.append("presentation profile set mismatch")
    for flow in flows:
        invalid = {row.get("scene") for row in flow.get("items", [])} - scenes
        if invalid:
            errors.append(f"invalid presentation scene refs: {sorted(invalid)}")
    badge_ids = {row["badge_id"] for row in read_json(DELIVERY_ROOT / "on_screen_truth_badges.json")["badges"]}
    required_badges = {"SIMULATED_ONLY", "HOST_VALIDATED", "LOGICAL_MODEL_SCALE", "DIRECT_COMPILE_LINK_ONLY", "REAL_DEVICE_NOT_EXECUTED", "OFFLINE_REPLAY"}
    if badge_ids != required_badges:
        errors.append("truth badge registry mismatch")
    for path in (DELIVERY_ROOT / name for name in required):
        text = path.read_text(encoding="utf-8", errors="replace")
        if str(ROOT) in text or re.search(r"C:\\Users\\|/home/[A-Za-z0-9._-]+/|ghp_[A-Za-z0-9]+|sk-[A-Za-z0-9]+", text):
            errors.append(f"secret/private path finding: {path.name}")
    if list(DELIVERY_ROOT.rglob("*.srt")) or list(DELIVERY_ROOT.rglob("*.vtt")):
        errors.append("final subtitle file created before timeline approval")
    if any(any(DELIVERY_ROOT.rglob(pattern)) for pattern in ("*.mp3", "*.wav", "*.m4a")):
        errors.append("audio created without approval")
    return {
        "schema_version": "g3-f-presentation-validation-v1", "status": "PASS" if not errors else "FAIL",
        "errors": errors, "narration_count": len(segments), "subtitle_count": len(subtitle_rows),
        "flow_profiles": sorted(row["profile"] for row in flows), "truth_badge_count": len(badge_ids),
        "language_status": narration.get("language_status"), "voiceover_created": narration.get("voiceover_created"),
        "sentinels": ["G3_F_NARRATION_OK", "G3_F_SUBTITLE_SOURCE_OK", "G3_F_PRESENTATION_FLOW_OK"] if not errors else [],
    }
